-- AlterTable
ALTER TABLE "site_settings" ADD COLUMN     "blanket" TEXT,
ADD COLUMN     "chappal" TEXT,
ADD COLUMN     "diwali" TEXT,
ADD COLUMN     "diwali2" TEXT,
ADD COLUMN     "diwali3" TEXT,
ADD COLUMN     "flag" TEXT,
ADD COLUMN     "hero_blankets" TEXT,
ADD COLUMN     "hero_education" TEXT,
ADD COLUMN     "hero_flood" TEXT,
ADD COLUMN     "hero_women" TEXT,
ADD COLUMN     "holi" TEXT,
ADD COLUMN     "holi2" TEXT,
ADD COLUMN     "holi3" TEXT,
ADD COLUMN     "joycation1" TEXT,
ADD COLUMN     "p_joycation" TEXT,
ADD COLUMN     "p_notebooks" TEXT,
ADD COLUMN     "p_rotibank" TEXT,
ADD COLUMN     "p_sanitary" TEXT;
