/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminVolunteersRouteImport } from './routes/admin.volunteers'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVolunteersRoute = AdminVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/donate'
    | '/events'
    | '/gallery'
    | '/projects'
    | '/sitemap.xml'
    | '/volunteer'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/messages'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/volunteers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/donate'
    | '/events'
    | '/gallery'
    | '/projects'
    | '/sitemap.xml'
    | '/volunteer'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/messages'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/volunteers'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/donate'
    | '/events'
    | '/gallery'
    | '/projects'
    | '/sitemap.xml'
    | '/volunteer'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/messages'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/volunteers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  ProjectsRoute: typeof ProjectsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VolunteerRoute: typeof VolunteerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/volunteers': {
      id: '/admin/volunteers'
      path: '/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AdminVolunteersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminVolunteersRoute: typeof AdminVolunteersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminVolunteersRoute: AdminVolunteersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  ProjectsRoute: ProjectsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VolunteerRoute: VolunteerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
